# Generated by Django 4.2.2 on 2023-06-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=30)),
                ('customer_supplier', models.CharField(max_length=50)),
                ('model_partname', models.CharField(max_length=30)),
                ('nonconf_quantity', models.CharField(max_length=10)),
                ('tot_lot_size', models.CharField(max_length=10)),
            ],
        ),
    ]
