# Generated by Django 4.2.2 on 2023-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_remove_formentry_nonconf_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='insp_report_if_rej',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='formentry',
            name='inspection_result',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='formentry',
            name='lanner_part_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='formentry',
            name='nonconf_quantity',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='formentry',
            name='serial_nums',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formentry',
            name='tot_lot_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='formentry',
            name='wo_po_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='customer_supplier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='inspector',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='model_partname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
