# Generated by Django 4.2.2 on 2023-07-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_formentry_insp_report_if_rej_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='case_num',
            field=models.CharField(default='', max_length=20),
        ),
    ]
