# Generated by Django 4.2.2 on 2023-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='formentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%Y%m%d-%H%M%S'),
        ),
    ]
