# Generated by Django 4.2 on 2023-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_delete_file_formentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='insp_report_if_rej',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='lanner_part_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='ncmr',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='serial_nums',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='wo_po_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
